name: CI
on:
  push:
    branches: [ "main" ]
env:
  TZ: "Asia/Jakarta"
  GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
  TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
jobs:
  build-jet-64:
    runs-on: buildjet-64vcpu-ubuntu-2204
    container:
      image: diazaji/clang:debian
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        apt update && apt upgrade -y
        ./ci.sh
