name: CI

on:
  schedule:
    - cron: '0 23 * * 0,2,4'
  workflow_dispatch:

env:
  TZ: "Asia/Jakarta"
  GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
  TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: diazaji/debian:clang
    steps:
    - uses: actions/checkout@v3
    - name: Build & Release
      run: |
        apt update && apt upgrade -y
        ./ci.sh
