name: CI

on:
  workflow_dispatch:

env:
  TZ: "Asia/Jakarta"
  GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
  TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"

jobs:
  build-profile:
    runs-on: ubuntu-latest
    container: diazaji/debian:clang
    steps:
    - uses: actions/checkout@v3
    - name: Generate Profile
      run: |
        ./ci.sh
        find build/llvm/instrumented -type f ! -name 'profdata.prof' -delete
    - uses: actions/cache/save@v3
      with:
        path: build/llvm/instrumented
        key: ${{ github.run_id }}
  build-final:
    needs: build-profile
    runs-on: ubuntu-latest
    container: diazaji/debian:clang
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache/restore@v3
      with:
        path: build/llvm/instrumented
        key: ${{ github.run_id }}
    - name: Build & Release
      run: |
        ./ci.sh final
